linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    - dogsled
    - dupl
    - gocognit
    - goconst
    - gocritic
    - godot
    - godox
    - gocyclo
    - nakedret
    - prealloc
    - unconvert
    - whitespace
    - predeclared
  disable: []

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  govet:
    enable-all: true

  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  staticcheck:
    checks: ["all"]

  nakedret:
    max-func-lines: 30

run:
  timeout: 5m
  tests: true
  go: "1.24"

issues:
  exclude-dirs:
    - test/mocks
  exclude-files:
    - ".*\\.generated\\.go$"
    - ".*vm_snapshot_create_handler_test\\.go$"
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec
        - gocognit
        - typecheck
    - path: test/integration/config/loader\.go
      linters:
        - typecheck
  max-issues-per-linter: 0
  max-same-issues: 0