// Code generated by MockGen. DO NOT EDIT.
// Source: internal/auth/jwt/claims.go
//
// Generated by this command:
//
//	mockgen -source=internal/auth/jwt/claims.go -destination=./test/mocks/auth/claims.go -package=mocks_auth
//

// Package mocks_auth is a generated GoMock package.
package mocks_auth
