server:
  host: "localhost"
  port: 8080
  readTimeout: 30s
  writeTimeout: 30s

database:
  driver: "sqlite"
  dsn: "file:/tmp/libgo-test.db?mode=rwc"
  maxOpenConns: 1
  maxIdleConns: 1
  connMaxLifetime: 1h
  autoMigrate: true

logging:
  level: "info"
  format: "json"
  outputPaths: ["stdout"]
  errorOutputPaths: ["stderr"]

libvirt:
  uri: "qemu:///system"
  poolName: "default"
  poolPath: "/tmp/exports"
  networkName: "default"
  connectionTimeout: 30s
  maxConnections: 5

storage:
  defaultPool: "default"
  poolPath: "/tmp/exports"

auth:
  jwtSecretKey: "test-secret-key-for-jwt-token-generation"
  tokenExpiration: 15m
  refreshTokenExpiration: 24h
  defaultUsers:
    - username: "admin"
      password: "admin"
      email: "admin@example.com"
      roles: ["admin"]

export:
  outputDir: "./tmp/exports"
  tempDir: "./tmp/exports"
  defaultFormat: "qcow2"
  retention: 24h
  formats:
    - "qcow2"
    - "vmdk"
    - "vdi"
    - "ova"

templatesPath: "configs/templates"
